### ISSUE TITLE
Big data load via AJAX issue

### ISSUE THREAD

**Issue by aleswita** [jiripudil/Naja#17]
I have page (big table) with default 10 rows and ajax pagination works fine.

When set more than 10 rows, paginate works only in Chrome..

Firefox console show me below error message:
![1](https://user-images.githubusercontent.com/6991688/44718747-5e29ae00-aac1-11e8-9a06-c95db463f2d0.PNG)

And Edge show me error below:
![2](https://user-images.githubusercontent.com/6991688/44718784-81545d80-aac1-11e8-8403-2d1baa07f652.PNG)

So, I'm doing something wrong? When swith to library to **nette.ajax,js**, all works fine.

**Comment by f3l1x** [comment]
> Meanwhile I'll try to come up with a better solution. I think a flag to entirely disable the caching and enforce the replay of the request on popstate would be a good starting point. What do you think?

Agreed.

**Comment by jiripudil** [comment]
Thanks for your opinions guys. I've made a first attempt at _an_ implementation (#18), let's find out if it actually makes sense. I'd be grateful if you reviewed and tested it please :)

**Comment by EdaCZ** [comment]
I also had this problem. Thanks for workaround! (And also thanks for this nice and modern library... :-) )

Maybe one note on README & doc: When I noticed this bug, it failed (from my point of view) on "some call of history API". I was confused, because I did not switched on some history extension or something like that. So, I thought that some extension for history is enabled by default. Fine. Let's turn it off. Then I found out that I can turn off work with history by `history: false` in options. So I added it to my initialization of Naja like this:

```
naja.initialize({
	history: false
});
```

But it did not helped. Then I googled the error message and found this issue... :-)

I know that from your point of view it could be all obvious, but from point of view of Naja-beginner it's different.

So, my suggestion is to note this in README / DOC that there is by default some work with history API and there can be such problem, when data are too big, so people can notice it early in the start.

And I have one more kind request: could you please add to `dist` directory also un-minified version of whole Naja? I'am using WebLoader, so source map is not working and it's payne to trace and debug those minified code, which is in `dist` now.

Thanks!

**Comment by jiripudil** [comment]
> Thanks for workaround! (And also thanks for this nice and modern library... :-) )

Hello and thank you :)

> So, my suggestion is to note this in README / DOC that there is by default some work with history API

Thanks for pointing that out. Where do you think is the right place for such notice? Maybe a new Known Issues page? Or in the Quick start? The documentation is in the `docs/` folder, feel free to open a PR and let's figure it out.

> So I added it to my initialization of Naja like this:

That won't work as you'd expect because passing the default options through `initialize` is not supported atm. But I can see no reason why it shouldn't be. Thanks for the incidental suggestion :)

> Could you please add to dist directory also un-minified version of whole Naja?

Sure. I'm in the middle of rewriting the build to a much simpler setup using rollup, so I'll just add this to the list of build artifacts and release it all in one go.

> I also had this problem.

Finally, @aleswita @EdaCZ could you please test the changes in #18 when you have some time? You can use `git@github.com:jiripudil/Naja.git#7f6c99e93aa6d89e3a2891727967d665225a246b` as the version constraint in npm, or I can build the branch and upload the dist file for you if you need it.

**Comment by EdaCZ** [comment]
> Thanks for pointing that out. Where do you think is the right place for such notice? Maybe a new Known Issues page? Or in the Quick start? The documentation is in the docs/ folder, feel free to open a PR and let's figure it out.
I would place it into Quick start as the last chapter after Usage.

> passing the default options through initialize is not supported 
Oh. So what is meant by those options in doc page:
> Similarly, you can keep a request off-the-record and not alter the browser's history at all by adding history: false to the options or data-naja-history="off" attribute to the element.
if its not options initialize options?
Now I see, that you are might talking about manual dispatching some request, but it was not clear to me.
Maybe you should explicitly specify about what options you are exactly talking about (also in here https://github.com/jiripudil/Naja/pull/18/files#diff-504226e3747990e65e4b28140ff27cbeR51 ).

> Sure. I'm in the middle of rewriting the build to a much simpler setup using rollup, so I'll just add this to the list of build artifacts and release it all in one go.
Great news! I look forward to it... :+1: 

Your patch #18 seems fine, I'll try it, thanks.

**Comment by jiripudil** [comment]
@EdaCZ thanks for your observations regarding the docs, they have been noted.

> I'll try it, but I need built file please.

Also, big thanks for offering to test the changes! I've added a link to the dist file in #18, please let's continue this part of the discussion there.
