### ISSUE TITLE
naja.historyHandler.popped always returns true

### ISSUE THREAD

**Issue by vylink** [jiripudil/Naja#9]
Hi,

is there any way to get information it the browser's "back button" was pressed within the 'beforeUpdate'?

```
naja.snippetHandler.addEventListener('afterUpdate', (event) => {
	//HERE I WANT TO KNOW IF THIS FUNC WAS CALLED BY HREF OR BROWSER'S BACK BUTTON

       const popped = naja.historyHandler.popped;  // always returns true

});
```

**Comment by jiripudil** [comment]
Hello,

I'm afraid there is currently no way of telling that. What is your use case? Maybe there could be other ways to achieve what you are after.

The `popped` field is only an internal helper to normalise the behaviour because some browsers dispatch popstate on page load, and some don't. It is set to true when any interaction with History API happens.

**Comment by vylink** [comment]
Hi Jiri,

Use case is simple. I want to "animate-in" when the standard link is clicked and "animate-out" when the back is pressed - I basically need to assign different class name when the back is pressd than standard link is clicked.

Any advice?

**Comment by jiripudil** [comment]
Hi,

I don't think it's a good idea to rely on this. What if the user clicks a link (animate-in), presses back (animate-out), and then goes forward again? It'd trigger popstate and re-render snippets from cache, but there's no deterministic way to tell if it was back or forward.

The safest option, I think, would be to animate things in reaction to DOM changes, e.g. via CSS transitions.

**Comment by jiripudil** [comment]
Closing this in hope that it's solved. Feel free to open another issue if you have further questions.
