### ISSUE TITLE
Spread operators in object literals cause crashes in Edge/EdgeHTML

### ISSUE THREAD

**Issue by dakur** [jiripudil/Naja#99]
# Bug Report

naja built source contains spread operator (`...`) in object literals, which is ES2018 feature. But Edge 12-18 (with EdgeHTML core) throws syntax error, because they implement only ES2015.

In the migration guide from v1 to v2, there is only mentioned that IE is no more supported, no mention about Edge. But `.browserslistrc` list `last 2 versions` which mean that old Edges with EdgeHTML core do not match anymore.

**Comment by jiripudil** [comment]
Hello, thanks for the report!

> It [Naja] is written using modern-day JavaScript, but compiled into a bundle that works in all modern browsers.

As far as I am aware, Windows users [should already have the Chromium-based Edge](https://www.theverge.com/2020/6/3/21279141/microsoft-edge-available-new-download-windows-update-rollout) which has auto-updates, and the legacy Edge will [no longer be supported as of next March](https://www.theverge.com/2020/8/17/21372487/microsoft-internet-explorer-11-support-end-365-legacy-edge), so it doesn't really count as a "modern browser" to me.

But you're right that this should be better clarified in the documentation. I'll take a look at it when I have a spare moment.

**Comment by dakur** [comment]
Well, that's true – for Win10 users only. :-\ So what do you suggest for those who need to support older Edges for people on older Win platforms? Switch back to naja v1?

The spread operator we are talking about is not a big deal I'd say – unlike XHR vs fetch issues. There are 5 occurences of it in whole naja. Still, I do not know if there will be any other problem once this would be fixed. 🤷‍♂️

**Comment by jiripudil** [comment]
Ok, good point. I am reconsidering this. As much as I'm not particularly in favour of it, since Win 8.1 is [obviously](https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet#section-2) still in the extended support period until 2023, it makes sense to "support" the legacy Edge as well.

However: does it auto-update? Do all users have the latest version (18)? If so, then it seems to be just a matter of the spread operator, which I'm willing to transpile. Supporting the whole legacy Edge range is a no go though, as the resulting bundle would be twice as big as it is now.

**Comment by jkuchar** [comment]
In corporate environments, support is usually even longer. It does makes sense to me to support old Edge as corporate users cannot update to new Edge even if they want. 😉

**Comment by dakur** [comment]
@jkuchar So you mean to support all versions of old Edge, or is Edge 18 enough like @jiripudil wrote above?

**Comment by dakur** [comment]
@jiripudil What about version 16+ (last 3 old versions). Are the bundle double size on all versions below 18?

**Comment by jkuchar** [comment]
3 old versions is totaly OK. I would think that even suporting current + two version before would be sufficent. This will cover cases when some machines are not updated for various reasons (e.g. someone is travelling and is always on mobile data, etc.)

**Comment by jiripudil** [comment]
Not double, no. But I'm not sure I like it, even if it's just an extra kilobyte.

Strictly speaking, Naja 2.0 has dropped support for Internet Explorer, a browser which [is still supported until August 2021](https://www.forbes.com/sites/quickerbettertech/2020/08/23/microsoft-is-killing-off-internet-explorerand-other-small-business-tech-news/#5e60c727d7f0), so supporting outdated versions of a browser which will lose support *five months earlier* seems a bit ridiculous 🙂 especially when [all Windows users](https://9to5google.com/2020/06/23/microsoft-edge-windows-7-8-update/) should automatically have updated to the Chromium-based Edge.

I'm willing to add `edge 18` to browserslist so that the bundled code works in it. But `playwright` cannot run legacy Edge anyway, so please be aware that I can't actually support it to such extent as to be able to guarantee that all tests pass and everything works.

**Comment by jiripudil** [comment]
I mean, you can always tweak your build configuration to further transpile `naja` if you need to support any ancient browser (Edge 16 is almost 3 years old). It just doesn't make sense to me for Naja itself to support anything else than the latest version.

**Comment by jkuchar** [comment]
I'm not sure about release cycle of old Edge. What I mean that we need to give at least month or two for sysadmins to update to latest version. It obviously does NOT make sense to support 3 years old Edge 16.

**Comment by dakur** [comment]
@jiripudil Yes, you're right. I did not know about the IE state. That said, it's pretty similar situation. So if you've decided to drop IE support, then it makes probably sense not to support Edge as well.

Maybe we can wait if someone else using naja will have such problem as well and decide then. Meanwhile, I can patch package or something in project.

**Comment by dakur** [comment]
I've created this quickly and not foundany further problems in Edge 18.

```
diff --git a/node_modules/naja/dist/Naja.esm.js b/node_modules/naja/dist/Naja.esm.js
index bd4b5c5..e61823c 100644
--- a/node_modules/naja/dist/Naja.esm.js
+++ b/node_modules/naja/dist/Naja.esm.js
@@ -1172,12 +1172,8 @@ class Naja extends EventTarget {
       url = url.href;
     }
 
-    options = { ...this.defaultOptions,
-      ...options,
-      fetch: { ...(this.defaultOptions.fetch || {}),
-        ...(options.fetch || {})
-      }
-    };
+    const fetchOptions = Object.assign({}, this.defaultOptions.fetch || {}, options.fetch || {});
+    options = Object.assign({}, this.defaultOptions, options, {fetch: fetchOptions});
 
     if (method.toUpperCase() === 'GET' && data instanceof FormData) {
       const urlObject = new URL(url, location.href);
@@ -1191,14 +1187,15 @@ class Naja extends EventTarget {
     }
 
     const abortController = new AbortController();
-    const request = new Request(url, {
-      credentials: 'same-origin',
-      ...options.fetch,
-      method,
-      headers: new Headers(options.fetch.headers || {}),
-      body: data !== null && Object.getPrototypeOf(data) === Object.prototype ? new URLSearchParams(data) : data,
-      signal: abortController.signal
-    }); // impersonate XHR so that Nette can detect isAjax()
+
+    const requestOptions = Object.assign({}, {
+		credentials: 'same-origin',
+		method,
+		headers: new Headers(options.fetch.headers || {}),
+		body: data !== null && Object.getPrototypeOf(data) === Object.prototype ? new URLSearchParams(data) : data,
+		signal: abortController.signal
+	}, options.fetch);
+    const request = new Request(url, requestOptions);
 
     request.headers.set('X-Requested-With', 'XMLHttpRequest');
```
